version: '3.8'
services:
  library-service:
    build: ./library-service
    ports:
      - "3000:3000"
    depends_on:
      - counter-service
      - mongodb
    environment:
      - PORT=3000 
      - MONGO_URL=mongodb://mongodb:27017/library

  counter-service:
    build: ./counter-service
    ports:
      - "4000:4000"
    volumes:
      - counter-data:/usr/src/app/src
    environment:
      - PORT=4000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  counter-data:
  mongo-data:

networks:
  default:
    driver: bridge